packages:
  - apps/*
  - packages/*

catalogs:
  default:
    '@changesets/changelog-github': ^0.5.0
    '@changesets/cli': 2.29.6
    '@commitlint/cli': ^19.8.1
    '@commitlint/config-conventional': ^19.8.1
    '@eslint/eslintrc': ^3.1.0
    '@eslint/js': ^9.13.0
    '@hookform/resolvers': 5.2.1
    '@icons-pack/react-simple-icons': 13.7.0
    '@langchain/community': 0.3.56
    '@langchain/core': 0.3.76
    '@langchain/google-genai': 0.1.10
    '@langchain/openai': 0.6.12
    '@nestjs/cli': ^10.4.5
    '@nestjs/common': ^10.4.5
    '@nestjs/config': ^4.0.2
    '@nestjs/core': ^10.4.5
    '@nestjs/jwt': ^11.0.0
    '@nestjs/passport': ^11.0.5
    '@nestjs/platform-express': ^10.4.5
    '@nestjs/schematics': ^10.0.0
    '@nestjs/swagger': ^7.4.2
    '@nestjs/testing': ^10.4.5
    '@prisma/client': 6.15.0
    '@radix-ui/react-avatar': ^1.1.10
    '@radix-ui/react-dialog': ^1.1.15
    '@radix-ui/react-dropdown-menu': ^2.1.16
    '@radix-ui/react-label': 2.1.7
    '@radix-ui/react-popover': ^1.1.15
    '@radix-ui/react-select': ^2.2.6
    '@radix-ui/react-separator': ^1.1.7
    '@radix-ui/react-slot': 1.2.3
    '@radix-ui/react-tooltip': ^1.2.8
    '@tailwindcss/postcss': 4.1.12
    '@tailwindcss/typography': ^0.5.16
    '@types/bcryptjs': ^2.4.6
    '@types/event-source-polyfill': 1.0.5
    '@types/express': ^5.0.0
    '@types/jest': ^29.5.12
    '@types/jsonwebtoken': ^9.0.3
    '@types/node': 18.18.0
    '@types/passport-jwt': ^4.0.1
    '@types/react': ^19
    '@types/react-dom': ^19
    '@types/supertest': ^6.0.2
    '@types/swagger-ui-express': ^4.1.6
    '@typescript-eslint/eslint-plugin': ^8.0.0
    '@typescript-eslint/parser': ^8.0.0
    '@typescript-eslint/typescript-estree': ^8.0.0
    '@uiw/react-md-editor': ^4.0.8
    bcryptjs: ^2.4.3
    chokidar: ^4.0.0
    class-transformer: ^0.5.1
    class-validator: ^0.14.2
    class-variance-authority: 0.7.1
    clsx: ^2.1.1
    concurrently: ^8.2.2
    dayjs: ^1.11.18
    eslint: ^9.34.0
    eslint-config-next: 15.5.2
    eslint-config-prettier: 9.1.2
    eslint-plugin-prettier: 5.5.4
    event-source-polyfill: 1.0.31
    globals: ^16.0.0
    husky: ^9.1.7
    inquirer: ^9.2.0
    jest: ^29.7.0
    jsonwebtoken: ^9.0.2
    lint-staged: ^16.1.5
    lucide-react: 0.542.0
    mint-filter: 1.1.2
    next: ^14.2.4
    next-auth: 4.24.11
    next-themes: ^0.4.6
    passport: ^0.7.0
    passport-jwt: ^4.0.1
    postcss: ^8.5.6
    prettier: 3.6.2
    prettier-plugin-tailwindcss: ^0.6.14
    prisma: 6.15.0
    react: ^18.3.1
    react-dom: ^18.3.1
    react-hook-form: 7.62.0
    react-markdown: 10.1.0
    reflect-metadata: ^0.2.2
    rxjs: ^7.8.1
    sonner: ^2.0.7
    source-map-support: ^0.5.21
    supertest: ^7.0.0
    swagger-ui-express: ^4.6.3
    tailwind-merge: ^3.3.1
    tailwindcss: ^4.1.12
    ts-jest: ^29.4.1
    ts-loader: ^9.5.1
    ts-node: ^10.9.2
    tw-animate-css: ^1.3.8
    typescript: 5.7.2
    typescript-eslint: ^8.4.2
    zod: ^3.23.8
    zustand: 5.0.8

ignoredBuiltDependencies:
  - bcrypt
