import type { Metadata } from 'next';
import Providers from './providers';
import AuthButton from './components/AuthButton';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body>
        <Providers>
          <AuthButton />
          {children}
        </Providers>
      </body>
    </html>
  );
}
